version: "3"

tasks:
  setup:
    desc: "Set up documentation environment and install dependencies"
    cmds:
      - uv pip install -r requirements.txt
    sources:
      - requirements.txt

  build:
    desc: "Build documentation"
    deps: [setup]
    env:
      # Environment-aware configuration for local builds
      DOCS_SITE_URL: "http://localhost:8000"
      DOCS_REPO_URL: ""
      DOCS_REPO_NAME: ""
      DOCS_EDIT_URI: ""
    cmds:
      - uv run mkdocs build --clean --config-file ../mkdocs.yml
    generates:
      - "../site/"

  serve:
    desc: "Serve documentation locally with hot reload"
    deps: [setup]
    env:
      # Environment-aware configuration for local development server
      DOCS_SITE_URL: "http://localhost:8000"
      DOCS_REPO_URL: ""
      DOCS_REPO_NAME: ""
      DOCS_EDIT_URI: ""
    cmds:
      - uv run mkdocs serve --dev-addr 127.0.0.1:8000 --livereload --config-file ../mkdocs.yml

  clean:
    desc: "Clean generated documentation files"
    cmds:
      - rm -rf ../site/
      - rm -rf ../.mkdocs_cache/

  all:
    desc: "Complete workflow: setup, build, and validate"
    cmds:
      - task: setup
      - task: build

  gitlab:
    desc: "Build documentation for GitLab Pages deployment"
    deps: [setup]
    env:
      # GitLab Pages specific configuration
      DOCS_SITE_URL: "https://$CI_PROJECT_NAMESPACE.gitlab.io/$CI_PROJECT_NAME"
      DOCS_REPO_URL: "$CI_PROJECT_URL"
      DOCS_REPO_NAME: "$CI_PROJECT_NAME"
      DOCS_EDIT_URI: "edit/main/docs/"
    cmds:
      - uv run mkdocs build --clean --config-file ../mkdocs.yml --site-dir ../public
